/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
	theme: {
		extend: {
			colors: {
				bg: "rgb(var(--bg) / <alpha-value>)",
				"bg-2": "rgb(var(--bg-2) / <alpha-value>)",
				fg: "rgb(var(--fg) / <alpha-value>)",
				line: "rgb(var(--fg) / 0.14)",
				lime: "#C6FF3D",
				cobalt: { DEFAULT: "#1B2AF0", deep: "#0A1470", light: "#5B6CFF" },
				sky: "#BFD8F5",
			},
			fontFamily: {
				sans: ["var(--font-sans)", "system-ui", "sans-serif"],
				mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
			},
			transitionTimingFunction: {
				out: "cubic-bezier(0.16, 1, 0.3, 1)",
				"66": "cubic-bezier(0.66, 0, 0.01, 1)",
			},
			typography: () => ({
				site: {
					css: {
						"--tw-prose-body": "rgb(var(--fg) / 0.8)",
						"--tw-prose-headings": "rgb(var(--fg))",
						"--tw-prose-links": "rgb(var(--fg))",
						"--tw-prose-bold": "rgb(var(--fg))",
						"--tw-prose-counters": "rgb(var(--fg) / 0.6)",
						"--tw-prose-bullets": "rgb(var(--fg) / 0.6)",
						"--tw-prose-hr": "rgb(var(--fg) / 0.14)",
						"--tw-prose-quotes": "rgb(var(--fg))",
						"--tw-prose-quote-borders": "rgb(var(--fg))",
						"--tw-prose-captions": "rgb(var(--fg) / 0.6)",
						"--tw-prose-code": "rgb(var(--fg))",
						"--tw-prose-pre-code": "#F2F2EE",
						"--tw-prose-pre-bg": "#191B1B",
						"--tw-prose-th-borders": "rgb(var(--fg) / 0.14)",
						"--tw-prose-td-borders": "rgb(var(--fg) / 0.14)",
						maxWidth: "none",
						h1: { fontWeight: "700", letterSpacing: "-0.03em" },
						h2: { fontWeight: "700", letterSpacing: "-0.03em" },
						h3: { fontWeight: "600", letterSpacing: "-0.02em" },
						h4: { fontWeight: "600" },
						a: {
							textDecoration: "underline",
							textUnderlineOffset: "3px",
							textDecorationColor: "rgb(var(--fg) / 0.4)",
							"&:hover": { textDecorationColor: "rgb(var(--fg))" },
						},
						code: {
							fontFamily: "var(--font-mono)",
							backgroundColor: "rgb(var(--fg) / 0.08)",
							borderRadius: "2px",
							padding: "0.15em 0.35em",
							fontWeight: "400",
						},
						"code::before": { content: "none" },
						"code::after": { content: "none" },
						pre: { borderRadius: "2px", border: "1px solid rgb(var(--fg) / 0.14)" },
						img: { border: "1px solid rgb(var(--fg) / 0.14)" },
						blockquote: { fontStyle: "normal", fontWeight: "500" },
					},
				},
			}),
		},
	},
	plugins: [require("@tailwindcss/typography")],
};
